In [1]:
# Get also a normally distributed random sample:
from scipy.stats import norm
import numpy as np

# Get random samples
n = 40

# Get random numbers, normally distributed, centered at 100, std=15
A = norm.rvs(size=n,loc=110,scale=10)
A = np.sort(A)
A = A.reshape((n,1))


# Get random numbers, normally distributed, centered at 95, std=10
B = norm.rvs(size=n,loc=108,scale=8)
B = np.sort(B)
B = B.reshape((n,1))

# Get random number, normally distributed, centered at 90, std=5
C = norm.rvs(size=n,loc=106,scale=8)
C = np.sort(C)
C = C.reshape((n,1))

In [2]:
AA = np.concatenate((A,B,C),axis=1)
AA

array([[  89.16257292,   94.0235168 ,   94.59414522],
       [  90.85762921,   95.27375542,   95.04064582],
       [  94.91299911,   96.61287006,   95.20047158],
       [  95.25406401,   96.81867257,   97.20580076],
       [  97.13629053,   97.76034244,   98.42884005],
       [  99.80999929,   99.16922734,   98.86776906],
       [ 101.09408697,   99.57928335,   99.79058113],
       [ 101.53142793,   99.6617583 ,  100.66992808],
       [ 101.98114804,  100.81235861,  101.7511548 ],
       [ 101.99306485,  102.27403543,  101.75163755],
       [ 102.75844065,  102.6879548 ,  102.42327983],
       [ 102.80828686,  102.70951457,  102.59745798],
       [ 103.77348132,  103.01492253,  102.97368886],
       [ 104.07439797,  103.88377283,  103.33875839],
       [ 105.65353689,  105.06976106,  103.3520918 ],
       [ 106.0451625 ,  105.12861188,  103.47495029],
       [ 106.87760493,  105.77267068,  104.59514159],
       [ 106.91414285,  106.16027689,  104.97382699],
       [ 108.56714541,  107.40899961,  105.16404611],
       [ 109.00103186,  108.14077396,  106.05787405],
       [ 111.27623952,  108.7944338 ,  106.22848249],
       [ 111.42801348,  108.85336251,  106.34728096],
       [ 113.33258496,  109.98786944,  106.50955334],
       [ 113.48644012,  110.48170743,  106.84870929],
       [ 113.65119057,  110.67413429,  107.21131303],
       [ 113.90581021,  110.74619671,  107.55105516],
       [ 114.61889547,  111.00463315,  108.95558009],
       [ 115.14608124,  111.55901563,  109.1772367 ],
       [ 115.28083186,  111.83744501,  109.68314548],
       [ 116.59197475,  112.1630496 ,  110.92298993],
       [ 116.62562334,  112.89850506,  111.35458865],
       [ 116.91680306,  113.33980118,  111.39981601],
       [ 117.76679505,  113.39674817,  111.73921357],
       [ 118.2280061 ,  117.28492803,  113.15957354],
       [ 120.42907723,  117.35243643,  113.75610169],
       [ 120.57659662,  117.55167066,  114.85307256],
       [ 124.20860277,  117.61068667,  115.12325836],
       [ 125.14658652,  119.18447276,  118.49235694],
       [ 126.96593383,  120.54786446,  128.293614  ],
       [ 133.30107607,  121.01541351,  129.55768519]])

In [3]:
import pandas as pd
df = pd.DataFrame.from_dict(AA)

In [4]:
df.columns=['BG 1', 'BG 2','BG 3']
df.index.name='Person ID'
df

                 BG 1        BG 2        BG 3
Person ID
0           89.162573   94.023517   94.594145
1           90.857629   95.273755   95.040646
2           94.912999   96.612870   95.200472
3           95.254064   96.818673   97.205801
4           97.136291   97.760342   98.428840
5           99.809999   99.169227   98.867769
6          101.094087   99.579283   99.790581
7          101.531428   99.661758  100.669928
8          101.981148  100.812359  101.751155
9          101.993065  102.274035  101.751638
10         102.758441  102.687955  102.423280
11         102.808287  102.709515  102.597458
12         103.773481  103.014923  102.973689
13         104.074398  103.883773  103.338758
14         105.653537  105.069761  103.352092
15         106.045162  105.128612  103.474950
16         106.877605  105.772671  104.595142
17         106.914143  106.160277  104.973827
18         108.567145  107.409000  105.164046
19         109.001032  108.140774  106.057874
20         111.276240  108.794434  106.228482
21         111.428013  108.853363  106.347281
22         113.332585  109.987869  106.509553
23         113.486440  110.481707  106.848709
24         113.651191  110.674134  107.211313
25         113.905810  110.746197  107.551055
26         114.618895  111.004633  108.955580
27         115.146081  111.559016  109.177237
28         115.280832  111.837445  109.683145
29         116.591975  112.163050  110.922990
30         116.625623  112.898505  111.354589
31         116.916803  113.339801  111.399816
32         117.766795  113.396748  111.739214
33         118.228006  117.284928  113.159574
34         120.429077  117.352436  113.756102
35         120.576597  117.551671  114.853073
36         124.208603  117.610687  115.123258
37         125.146587  119.184473  118.492357
38         126.965934  120.547864  128.293614
39         133.301076  121.015414  129.557685

In [5]:
df.to_csv('BG-db.csv')